### ISSUE TITLE
Header consistency

### ISSUE THREAD

**Issue by margeschrec** [vricci518/barbill#16]
work on header consistency

**Comment by billythakidd04** [comment]
What does this mean? What needs to be done? Need more specifics.

**Comment by vricci518** [comment]
Make headers consistent in color and positioning across the pages.
Use the Orange color for headings #C03832

**Comment by margeschrec** [comment]
thank you for clarifying Vincent

**Comment by billythakidd04** [comment]
@margeschrec why was this closed? Has it been completed?

**Comment by margeschrec** [comment]
yes it has

**Comment by margeschrec** [comment]
#16 done
