### ISSUE TITLE
Menu Pages

### ISSUE THREAD

**Issue by vricci518** [vricci518/barbill#36]
Add Bootstrap to Menu and Takeout pages for both location.
Adjust Info links by adding class="dropdown-item" to each link

**Comment by vricci518** [comment]
#37 menu pages completed info links corrected

**Comment by billythakidd04** [comment]
> #37 menu pages completed info links corrected

Just fyi if you add `closes #<whateever ticket number>` in the pull request main body, it will automatically close the ticket for you.
